const BASE_API_URL = process.env.BASE_API_URL || 'http://localhost:3001';

const NUM_OF_CUSTOMERS_TO_SHOW_DROPDOWN_OPTIONS = [10, 25, 50, 100]

const MIN_PASSWORD_LENGTH = 4;

const TOTAL_CUSTOMER_PAGES = 100;

const TOTAL_ACCOUNTS_PAGES = 2;

export { BASE_API_URL, MIN_PASSWORD_LENGTH, NUM_OF_CUSTOMERS_TO_SHOW_DROPDOWN_OPTIONS, TOTAL_ACCOUNTS_PAGES, TOTAL_CUSTOMER_PAGES };

