const BASE_API_URL = process.env.BASE_API_URL || 'http://localhost:3001';

const NUM_OF_CUSTOMERS_TO_SHOW_DROPDOWN_OPTIONS = [10, 25, 50, 100]

const ADMIN_USER_NAMES = ['admin'];

const MIN_PASSWORD_LENGTH = 4;

export { ADMIN_USER_NAMES, BASE_API_URL, MIN_PASSWORD_LENGTH, NUM_OF_CUSTOMERS_TO_SHOW_DROPDOWN_OPTIONS };

